config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }

  root 'tweets#index'
  resources :profiles, only: %i[show]
  resources :tweets, only: %i[index show new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  delegate :username, to: :user
  validates :content,
            presence: true,
            length: { minimum: 1, maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  devise :database_authenticatable,
         :registerable,
         :validatable
  has_many :tweets, dependent: :destroy
  validates :username,
            uniqueness: true,
            presence: true,
            length: { minimum: 4, maximum: 20 },
            format: { with: /\A[a-zA-Z0-9]+\z/ }
  validates :email,
            uniqueness: true,
            presence: true
# FIXME: モデル分ける必要あるかも
#   validates :profile,
#             length: { maximum: 200 }
#   validates :url,
#             format: /\A#{URI::DEFAULT_PARSER.make_regexp(%w[http https])}\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[email profile url])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[show]

  def show; end

  private

  def set_profile
    @user = User.find(params[:id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[show]
  before_action :authenticate_user!, only: %i[new create]

  def index
    @tweets = Tweet.order(updated_at: :DESC)
  end

  def show; end

  def new
    @tweet = current_user.tweets.build
  end

  def create
    @tweet = current_user.tweets.build(tweet_params)
    if @tweet.save
      redirect_to root_path, notice: 'ツイートしました。'
    else
      render 'new', status: :unprocessable_entity
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:content)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.haml
%footer.navbar.fixed-bottom.justify-content-center.bg-primary
  %small.c-white
    © XXX Inc.

app/views/layouts/_header.html.haml
%header
  .navbar.navbar-expand-md.fixed-top.bg-primary
    .col-md-4
      = link_to root_path, class: 'c-white' do
        = image_tag 'logo.png', alt: 'Home', class: 'logo ms-2'

    .col-md-4.d-flex.justify-content-center.c-white
      = notice

    .col-md-4.d-flex.justify-content-end.align-self-end
      %ul.navbar-nav
        %li
          - if user_signed_in?
            = link_to 'プロフィール', edit_user_registration_path, class: 'btn c-white'
        %li
          - if user_signed_in?
            = link_to 'ログアウト', destroy_user_session_path, data: { turbo_method: :delete }, class: 'btn c-white'
            -# TODO: FIXME: GET 以外のメソッドは link_to を使わないこと
          - else
            = link_to 'ログイン', new_user_session_path, class: 'btn c-white'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Microblog
    %meta{name: 'viewport', content: 'width=device-width,initial-scale=1'}
    %meta{charset: 'utf-8'}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', defer: true

  %body.bg-light.ff.pt-5.d-flex.justify-content-center.pb-5
    = render 'layouts/header'
    = yield
    = render 'layouts/footer'

app/views/profiles/show.html.haml
.mt-5.w-500p
  .mb-1
    = link_to 'ホーム', root_path, class: 'btn btn-primary c-white'

  .bg-white.border.rounded-3.c-darkgray.lh-base.mb-1.p-3
    %p.fs-2
      = @user.username
    .fs-3.lh-base
      = simple_format h(@user.profile)
    .fs-6
      = link_to @user.url, @user.url, target: :_blank, rel: 'noopener noreferrer'
    .text-center.mt-4
      - if user_signed_in? && @user.id === current_user.id
        = link_to '編集', edit_user_registration_path, class: 'btn btn-primary c-white'

app/views/tweets/index.html.haml
.mt-5.w-500p
  .d-flex.flex-row-reverse
    - if user_signed_in?
      = link_to '＋', new_tweet_path, class: 'btn btn-primary c-white fs-2 rounded-30p p-fixed m-2'

  - @tweets.each do |tweet|
    = link_to(tweet_path(tweet), class: 'text-decoration-none') do
      .bg-white.border.rounded-3.c-darkgray.lh-base.mb-1.p-3
        .row.mb-1
          .col-md-7
            %strong
              = tweet.username
          .col-md-5.text-end.c-gray
            %small
              = l(tweet.updated_at, format: :long)
        .row
          .col-md-12
            .fs-5
              = simple_format h(tweet.content)

app/views/tweets/new.html.haml
.mt-5.w-500p
  .mb-1
    = link_to 'ホーム', root_path, class: 'btn btn-primary c-white'

  .bg-white.border.rounded-3.p-3
    = simple_form_for @tweet do |f|
      = f.input :content, as: :text, placeholder: 'いまどうしてる？', label: false, input_html: { class: 'h-250p' }
      .text-center.mt-4
        = f.button :submit, 'ツイート', class: 'btn btn-primary c-white'

app/views/tweets/show.html.haml
.mt-5.w-500p
  .mb-1
    = link_to 'ホーム', root_path, class: 'btn btn-primary c-white'

  .bg-white.border.rounded-3.c-darkgray.p-3
    %strong.fs-5
      = @tweet.username
    .fs-2.lh-base.mt-2
      = simple_format h(@tweet.content)
    .fs-6.c-gray
      = l(@tweet.updated_at, format: :long)
    .text-center.mt-1
      = link_to 'プロフィール', profile_path(@tweet.user), class: 'btn btn-primary c-white'

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "ログイン", new_session_path(resource_name)

- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "アカウント作成", new_registration_path(resource_name)